eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8804
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-service-order-feign/**
      service-id: service-order-feign
    api-b:
      path: /api-order/**
      service-id: service-order
